import type { Metadata } from "next";
import Providers from "./providers";
import { Box } from "@mui/material";
import Navbar from "../navigation/Navbar";
import Header from "@/header/Header";
import "../globals.css"

export const metadata: Metadata = {
  title: "My Budget App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body style={{ margin: 0, padding: 0 }}>
        <Providers>
          <Box sx={{ display: "flex", flexDirection: "row", height: "100vh" }}>
            {/* Nav / Sidebar */}
            <Box
              className="hidden lg:block"
              component="nav"
              sx={{
                minWidth: 250,
                bgcolor: "background.paper",
                borderRight: 2,
                borderColor: "divider",
              }}
            >
              <Navbar/>
            </Box>

            {/* Main column */}
            <Box sx={{ display: "flex", flexDirection: "column", width: "100%" }}>
                {/* Header */}
                <Box
                  component="header"
                  sx={{
                    width: "100%",
                    bgcolor: "primary.main",
                    borderBottom: 2,
                    borderColor: "divider",
                  }}
                >
                  <Header />
                </Box>

              {/* Main content */}
              <Box
                component="main"
                sx={{
                  display: "flex",
                  flex: 1,
                  bgcolor: "background.default",
                  color: "text.primary",
                  overflow: "hidden",
                  overflowY: "scroll"
                }}
              >
                {children}
              </Box>
            </Box>
          </Box>
        </Providers>
      </body>
    </html>
  );
}
